plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
def targetJavaVersion = 25


repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = "transferable_pets_tests"
        enableClientGameTests = false
    }
}

processResources {
    def metadata = [
            mod_name: project.mod_name,
            mod_id: project.mod_id,
            mod_version: project.version,
            mod_description: project.mod_description,
            repository: project.repository,
            license: project.license,
            mod_icon: project.mod_icon,
            environment: project.environment,
            minecraft_version: project.minecraft_version,
            loader_version: project.loader_version,
            fabric_version: project.fabric_version,
            java_version: targetJavaVersion
    ]
    inputs.properties metadata
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand metadata
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = targetJavaVersion
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    withSourcesJar()
}

base {
    archivesName = project.mod_id + project.generated_file_name_addon
}

jar {
    def modId = project.mod_id
    inputs.property "modId", modId
    from("LICENSE") {
        rename { "${it}_${modId}" }
    }
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
