# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Mod Properties
mod_name=Transferable Pets
mod_id=transferable_pets
generated_file_name_addon=-[26.3]
mod_version=1.0.6
mod_description=Transferable Pets is a mod that allows you to transfer your pets to other players. Mod page: https://modrinth.com/mod/transferable-pets
mod_icon=assets/transferable_pets/icon.png
repository=https://github.com/lnr0626/Transferable_Pets
license=CC-BY-NC-4.0
environment=*
maven_group=winterwolfsv
# Dependencies
# check this on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.21
# Fabric API
fabric_version=0.161.0+26.3